version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: yoneodoo-postgres
    ports:
      - "5433:5432"  # 내 PC의 5433 포트를 도커 내부의 5432로 연결 (충돌 방지!)
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: yoneodoo
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: