spring:
  datasource:
    # 1. 방금 받은 주소 앞에 'jdbc:' 를 붙여서 통째로 넣습니다.
    url: jdbc:postgresql://ep-lucky-band-a1jwkc0u.ap-southeast-1.aws.neon.tech/neondb?sslmode=require

    # 2. 아이디와 비밀번호도 쏙쏙 빼서 넣습니다.
    username: neondb_owner
    password: npg_8ShFrg5vBQWH

    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
  file:
    name: ""